#Inputs the number of each amino acid and outputs the three highest peaks of the theoretical mass spectra
aminoAcidToThreeHighest <- function(A,C,D,E,F,G,H,I,K,L,M,N,P,Q,R,S,T,V,W,Y) {
  
  #each amino acid is represented as a vector with its count of C, H, O, N, and S
  ala <- c(3,7,1,2,0)
  cys <- c(3,7,1,2,1)
  asp <- c(4,7,1,4,0)
  glu <- c(5,9,1,4,0)
  phe <- c(9,11,1,2,0)
  gly <- c(2,3,1,2,0)
  his <- c(6,9,3,2,0)
  ile <- c(6,13,1,2,0)
  lys <- c(6,14,2,2,0)
  leu <- c(6,13,1,2,0)
  met <- c(5,11,1,2,1)
  asp <- c(4,7,1,4,0)
  pro <- c(5,9,1,2,0)
  gln <- c(5,10,2,3,0)
  arg <- c(6,14,4,2,0)
  ser <- c(3,7,1,3,0)
  thr <- c(4,9,1,3,0)
  val <- c(5,11,1,2,0)
  trp <- c(11,12,2,2,0)
  tyr <- c(9,11,1,3,0)
  
  #this stores the number of amino acids in the sequence inputted
  aminoAcidNumber <- A + C + D + E + F + G + H + I + K + L + M + N + P + Q + R + S + T + V + W + Y
  #this stores the number of peptide bonds, so that the appropriate number of H and O can be subtracted from the final atom count
  bondCount <- aminoAcidNumber - 1
  
  #counts the number of C
  v <- A*ala[1] + C*cys[1] + D*asp[1] + E*glu[1] + F*phe[1] + G*gly[1] + H*his[1] + I*ile[1] + 
    K*lys[1] + L*leu[1] + M*met[1] + N*asp[1] + P*pro[1] + Q*gln[1] + R*arg[1] + S*ser[1] + T*thr[1] +
    V*val[1] + W*trp[1] + Y*tyr[1]
  #counts the number of H
  w <- A*ala[2] + C*cys[2] + D*asp[2] + E*glu[2] + F*phe[2] + G*gly[2] + H*his[2] + I*ile[2] + 
    K*lys[2] + L*leu[2] + M*met[2] + N*asp[2] + P*pro[2] + Q*gln[2] + R*arg[2] + S*ser[2] + T*thr[2] +
    V*val[2] + W*trp[2] + Y*tyr[2] - 2*bondCount
  #counts the number of O
  x <- A*ala[3] + C*cys[3] + D*asp[3] + E*glu[3] + F*phe[3] + G*gly[3] + H*his[3] + I*ile[3] + 
    K*lys[3] + L*leu[3] + M*met[3] + N*asp[3] + P*pro[3] + Q*gln[3] + R*arg[3] + S*ser[3] + T*thr[3] +
    V*val[3] + W*trp[3] + Y*tyr[3]
  #counts the number of N
  y <- A*ala[4] + C*cys[4] + D*asp[4] + E*glu[4] + F*phe[4] + G*gly[4] + H*his[4] + I*ile[4] + 
    K*lys[4] + L*leu[4] + M*met[4] + N*asp[4] + P*pro[4] + Q*gln[4] + R*arg[4] + S*ser[4] + T*thr[4] +
    V*val[4] + W*trp[4] + Y*tyr[4] - bondCount
  #counts the number of S
  z <- A*ala[5] + C*cys[5] + D*asp[5] + E*glu[5] + F*phe[5] + G*gly[5] + H*his[5] + I*ile[5] + 
    K*lys[5] + L*leu[5] + M*met[5] + N*asp[5] + P*pro[5] + Q*gln[5] + R*arg[5] + S*ser[5] + T*thr[5] +
    V*val[5] + W*trp[5] + Y*tyr[5]
  
  #stores the theoretical distribution generated by these amino acids
  matrixx <- mSDistributionBF(v,w,x,y,z,2)
  #takes the three highest peaks from the theoretical data
  result <- threeHighestVal(matrixx)
  
  return(result)
}